compressionLevel: mixed

enableGlobalCache: true

nmHoistingLimits: none

nodeLinker: node-modules

plugins:
  - checksum: 0141f8cfb8a5ea41428cc0a49cf412f0cf13a3f3f9e51ef354768b5c988c93d0adc46c318d11b6da858b9ce9a9c8db0069712c10be35f9ac440071bc00bc4216
    path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://mskelton.dev/yarn-outdated/v3"

yarnPath: .yarn/releases/yarn-4.0.1.cjs
