name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=5120"
      YARN_CACHE_FOLDER: ./.yarn/cache
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: install
        run: yarn install
      - name: build
        run: yarn build
